# 使用 Node.js 镜像作为基础镜像
FROM node:20-alpine as build

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json 到工作目录
COPY package*.json ./

# 安装依赖
RUN npm install --registry https://registry.npmmirror.com

# 复制其他源代码文件到工作目录
COPY . .

# 构建项目
RUN npm run build

# 使用 Nginx 镜像作为基础镜像
FROM nginx:stable-alpine

# 将构建好的文件复制到 Nginx 的托管目录
COPY --from=build /app/build /usr/share/nginx/html

# 复制 Nginx 配置文件
COPY default.conf /etc/nginx/conf.d/

# 暴露端口 80
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]